spring.application.name=appTp3Produtos

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
#spring.datasource.url=jdbc:mysql://localhost/dbJavaNoite?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=GMT
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create
springdoc.swagger-ui.path=/swagger-ui/
springdoc.version=0.0.1

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Habilitar o console H2
spring.h2.console.enabled=true