apiVersion: v1
kind: Service
metadata:
  name: ufology-redis-service
  namespace: ufology
spec:
  type: ClusterIP
  selector:
    app: ufology-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
